#!/usr/bin/bash

if [ -z "$1" ] ; then
  echo "usage: $0 <trunk>"
  exit 1
fi

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

readarray -t branches <<< "$("${SCRIPT_DIR}"/git-branches-not-on-remote)"
for b in "${branches[@]}" ; do
  # echo ">branch: ${b}" 1>&2
  min_behind=0
  min_ahead=0
  for trunk in "$@" ; do
    behind="$("${SCRIPT_DIR}"/git-commits-behind "${trunk}" "${b}")"
    if [ "${min_behind}" -gt "${behind}" ] ; then
      min_behind="${behind}"
    fi
    ahead="$("${SCRIPT_DIR}"/git-commits-ahead "${trunk}" "${b}")"
    if [ "${min_ahead}" -gt "${ahead}" ] ; then
      min_ahead="${ahead}"
    fi
    # echo "> ${trunk} behind: ${behind}" 1>&2
    # echo "> ${trunk} ahead: ${ahead}" 1>&2
  done
  if [ "${min_ahead}" != 0 ] ; then
    echo "${b} ${min_behind}:${min_ahead}"
  fi
done
